---
- name: Check and Enable Windows Update Service
  hosts: windows
  gather_facts: false
  
  tasks:
    - name: Check Windows Update service status
      win_service:
        name: wuauserv
      register: service_status
      
    - name: Display current service status
      debug:
        msg: |
          Windows Update Service Status:
          - Name: {{ service_status.name }}
          - State: {{ service_status.state }}
          - Start Mode: {{ service_status.start_mode }}
          - Status: {{ service_status.status }}
          
    - name: Enable Windows Update service (set to auto start)
      win_service:
        name: wuauserv
        start_mode: auto
      when: service_status.start_mode != 'auto'
      
    - name: Start Windows Update service
      win_service:
        name: wuauserv
        state: started
      when: service_status.state != 'started'
      
    - name: Verify service is running
      win_service:
        name: wuauserv
        state: started
      register: final_status
      
    - name: Display final status
      debug:
        msg: "Windows Update service is now {{ final_status.state }} and will start {{ final_status.start_mode }}" 