---
- name: Install Jenkins on Rocky Linux 9
  hosts: jenkins_servers
  become: yes

  tasks:
    - name: Install Java (OpenJDK 17)
      dnf:
        name: java-17-openjdk
        state: present
        name: java-17-openjdk-devel
        state: present

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'

    - name: Import Jenkins repository GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      dnf:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes