---
- name: Configure Jenkins Firewall Exceptions for Rocky Linux 9
  hosts: jenkins_servers
  become: yes
  vars:
    jenkins_port: 8080
    jenkins_agent_port: 50000

  tasks:
    - name: Check if firewalld is running
      systemd:
        name: firewalld
      register: firewalld_status
      check_mode: no

    - name: Configure firewalld for Jenkins (if firewalld is active)
      block:
        - name: Add Jenkins HTTP port to firewalld
          firewalld:
            port: "{{ jenkins_port }}/tcp"
            permanent: yes
            state: enabled
          notify: reload firewalld

        - name: Add Jenkins agent port to firewalld
          firewalld:
            port: "{{ jenkins_agent_port }}/tcp"
            permanent: yes
            state: enabled
          notify: reload firewalld

        - name: Add Jenkins service to firewalld (alternative method)
          firewalld:
            service: jenkins
            permanent: yes
            state: enabled
          notify: reload firewalld
          ignore_errors: yes

      when: firewalld_status.status.ActiveState == "active"

    - name: Configure iptables for Jenkins (if firewalld is not active)
      block:
        - name: Ensure iptables service is running
          systemd:
            name: iptables
            state: started
            enabled: yes

        - name: Add Jenkins HTTP port to iptables INPUT chain
          iptables:
            chain: INPUT
            protocol: tcp
            destination_port: "{{ jenkins_port }}"
            jump: ACCEPT
            comment: "Jenkins HTTP port"
            action: insert
            rule_num: 1

        - name: Add Jenkins agent port to iptables INPUT chain
          iptables:
            chain: INPUT
            protocol: tcp
            destination_port: "{{ jenkins_agent_port }}"
            jump: ACCEPT
            comment: "Jenkins agent port"
            action: insert
            rule_num: 2

        - name: Save iptables rules
          shell: service iptables save
          args:
            creates: /etc/sysconfig/iptables

      when: firewalld_status.status.ActiveState != "active"

    - name: Verify Jenkins ports are accessible
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ jenkins_port }}"
        timeout: 30
      delegate_to: localhost
      run_once: yes

  handlers:
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded 