---
- name: Shutdown VMs - macOS, Windows, and Linux
  hosts: macOS,linux,windows
  gather_facts: false
  
  tasks:
    - name: Display shutdown message
      debug:
        msg: "Shutting down {{ inventory_hostname }} ({{ ansible_os_family }})"
      when: ansible_os_family is defined

---
- name: Shutdown Windows VMs
  hosts: windows
  gather_facts: false
  
  tasks:
    - name: Shutdown Windows system
      win_shutdown:
        msg: "System shutdown initiated by Ansible"
        timeout: 30
        force: yes
      register: shutdown_result
      
    - name: Display shutdown status
      debug:
        msg: "Windows VM {{ inventory_hostname }} shutdown initiated"

---
- name: Shutdown Linux VMs
  hosts: linux
  become: yes
  gather_facts: false
  
  tasks:
    - name: Shutdown Linux system
      command: shutdown -h now
      async: 0
      poll: 0
      register: shutdown_result
      
    - name: Display shutdown status
      debug:
        msg: "Linux VM {{ inventory_hostname }} shutdown initiated"

---
- name: Shutdown macOS VMs
  hosts: macOS
  become: yes
  gather_facts: false
  
  tasks:
    - name: Shutdown macOS system
      command: shutdown -h now
      async: 0
      poll: 0
      register: shutdown_result
      
    - name: Display shutdown status
      debug:
        msg: "macOS VM {{ inventory_hostname }} shutdown initiated" 