---
- name: Install Apache Tomcat on Rocky Linux
  hosts: all
  become: yes

  vars:
    tomcat_version: 10.1.24
    tomcat_user: tomcat
    tomcat_group: tomcat
    install_dir: /opt/tomcat
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Install Java (OpenJDK)
      yum:
        name: java-11-openjdk
        state: present

    - name: Create Tomcat group
      group:
        name: "{{ tomcat_group }}"
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false
        system: yes
        create_home: no

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz

    - name: Create installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Set permissions
      file:
        path: "{{ install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: (Optional) Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}

          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_PID={{ install_dir }}/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ install_dir }}"
          Environment="CATALINA_BASE={{ install_dir }}"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

          ExecStart={{ install_dir }}/bin/startup.sh
          ExecStop={{ install_dir }}/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        enabled: yes