- name: Update Linux machines
  hosts: linux
  become: yes
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (RHEL/CentOS/Amazon Linux)
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Upgrade all packages (RHEL/CentOS/Amazon Linux)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
